name: q2chat

services:
  frontend:
    build:
      context: frontend
      dockerfile: frontend.dockerfile
    depends_on:
      - backend
    volumes:
    - ./frontend:/usr/src/frontend
    ports:
      - "3000:3000"

  backend:
    build:
      context: backend
      dockerfile: backend.dockerfile
    volumes:
      - ./backend:/usr/src/backend
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env